"""
Cluster-Specific Pill Exclusions — defines which pills are contraindicated
for each patient cluster.

This module is loaded by the Safe Gate Engine to filter pills based on the
cluster assignment. Each cluster has a list of combo_ids (from pill_reference_db.csv)
that should be excluded before the agent sees the candidate pool.

SOURCE OF TRUTH:
    models/clustering/artifacts/profile_rules.json  (generated by train_profiles.py)

Profiles are derived from a 12-component GMM trained on patient features.
Blocking rules are WHO MEC-based: Cat 4 conditions trigger at ≥15% cluster
prevalence; Cat 3 conditions at ≥25% cluster prevalence.

Pill IDs map to pill_reference_db.csv combo_id values.
Profile N (from profile_rules.json) maps to cluster key "cluster_N" here.

Profile descriptions (from CLUSTERING_MODEL.md):
    0  Rheum. Arthritis + Sleep Apnea   → ALL 9 pills blocked (hypertension + liver disease rules)
    1  Migraine + Depression             → NONE blocked
    2  Diabetes + Breast Cancer          → ALL 9 pills blocked (breast cancer blocks minipill)
    3  Hypertension + Diabetes           → 8 combined OCPs blocked; minipill (NET_PO_350) available
    4  Thrombophilia + Endometriosis     → 8 combined OCPs blocked; minipill available
    5  Baseline / Low-Risk               → NONE blocked
    6  PCOS + Thrombophilia              → ALL 9 pills blocked (epilepsy + thrombophilia combination)
    7  Epilepsy                          → 8 combined OCPs blocked; minipill available
    8  PCOS + Hypertension               → 8 combined OCPs blocked; minipill available
    9  PCOS                              → NONE blocked
    10 Hypertension + Migraine+Aura      → 8 combined OCPs blocked; minipill available
    11 Hypertension + Thrombophilia      → 8 combined OCPs blocked; minipill available

These exclusions are applied IN ADDITION to the per-patient hard constraint rules
in safe_gate.py. The complete filtering logic is:
1. Apply hard constraints (patient-specific contraindications)
2. Apply cluster exclusions (population-level risk patterns from GMM)
3. Return filtered candidate pool to the agent
"""

import logging
from typing import Dict, List

logger = logging.getLogger(__name__)

# ── All combined OCP combo_ids (8 pills) ───────────────────────────────────
_ALL_COMBINED = [
    "EE20_LNG90",
    "EE30_LNG150",
    "EE35_NET500_1000",
    "EE20_NET1000",
    "EE25_35_NGM",
    "EE30_DSG150",
    "EE30_DRSP3",
    "EE20_DRSP3",
]

# All 9 pills (combined + minipill)
_ALL_PILLS = _ALL_COMBINED + ["NET_PO_350"]

# ── Cluster Exclusion Configuration ────────────────────────────────────────
# Source: models/clustering/artifacts/profile_rules.json → profiles[N]["all_blocked_ids"]
# Key format: "cluster_N" where N matches the profile integer key in profile_rules.json
#
CLUSTER_EXCLUSIONS: Dict[str, List[str]] = {
    # Profile 0: Rheum. Arthritis + Sleep Apnea
    # Hypertension (42.9%) + liver-disease-adjacent risk → all 9 pills blocked
    "cluster_0": _ALL_PILLS,

    # Profile 1: Migraine + Depression
    # No WHO MEC blocking conditions at threshold → no pills blocked
    "cluster_1": [],

    # Profile 2: Diabetes + Breast Cancer
    # Breast cancer (Cat 4) blocks ALL hormonal pills including minipill
    "cluster_2": _ALL_PILLS,

    # Profile 3: Hypertension + Diabetes
    # Hypertension + Diabetes (Cat 3) block all combined OCPs; minipill safe
    "cluster_3": _ALL_COMBINED,

    # Profile 4: Thrombophilia + Endometriosis
    # Thrombophilia + Migraine-with-aura (Cat 4) block all combined OCPs; minipill safe
    "cluster_4": _ALL_COMBINED,

    # Profile 5: Baseline / Low-Risk
    # No blocking conditions → no pills blocked
    "cluster_5": [],

    # Profile 6: PCOS + Thrombophilia
    # Thrombophilia + Epilepsy combination → all 9 pills blocked
    "cluster_6": _ALL_PILLS,

    # Profile 7: Epilepsy
    # Epilepsy AED interactions (Cat 3) block combined OCPs; minipill unaffected
    "cluster_7": _ALL_COMBINED,

    # Profile 8: PCOS + Hypertension
    # Hypertension (Cat 3) + Migraine block combined OCPs; minipill safe
    "cluster_8": _ALL_COMBINED,

    # Profile 9: PCOS
    # No blocking conditions at threshold → no pills blocked
    "cluster_9": [],

    # Profile 10: Hypertension + Migraine+Aura
    # Migraine-with-aura (Cat 4) + Hypertension (Cat 3) block combined OCPs; minipill safe
    "cluster_10": _ALL_COMBINED,

    # Profile 11: Hypertension + Thrombophilia
    # Thrombophilia (Cat 4) + Hypertension + Diabetes block combined OCPs; minipill safe
    "cluster_11": _ALL_COMBINED,

    # ── DEFAULT ─────────────────────────────────────────────────────────────
    # Used when cluster is unknown or assignment failed.
    # Conservative: no cluster-specific exclusions (rely on hard constraints only).
    "default": [],
}


def get_excluded_pills_for_cluster(cluster_profile: str) -> List[str]:
    """
    Return the list of pill_ids that should be excluded for the given cluster.
    Falls back to empty list if cluster not found (no cluster-specific exclusions).
    
    Args:
        cluster_profile: Cluster identifier (e.g. "cluster_0", "cluster_1")
    
    Returns:
        List of pill_ids to exclude
    """
    # Handle low-confidence cluster assignments (dict format)
    if isinstance(cluster_profile, dict):
        profile_str = cluster_profile.get("profile", "default")
    else:
        profile_str = cluster_profile or "default"
    
    excluded = CLUSTER_EXCLUSIONS.get(profile_str, CLUSTER_EXCLUSIONS["default"])
    
    if excluded:
        logger.info(
            "Cluster '%s': excluding %d pills — %s", 
            profile_str, len(excluded), excluded
        )
    else:
        logger.info("Cluster '%s': no cluster-specific exclusions", profile_str)
    
    return excluded


def add_cluster_exclusion(cluster_profile: str, pill_id: str) -> None:
    """
    Dynamically add a pill exclusion for a cluster (useful for testing or runtime config).
    
    Args:
        cluster_profile: Cluster identifier
        pill_id: Pill ID to exclude
    """
    if cluster_profile not in CLUSTER_EXCLUSIONS:
        CLUSTER_EXCLUSIONS[cluster_profile] = []
    
    if pill_id not in CLUSTER_EXCLUSIONS[cluster_profile]:
        CLUSTER_EXCLUSIONS[cluster_profile].append(pill_id)
        logger.info("Added exclusion: cluster '%s' → pill '%s'", cluster_profile, pill_id)


def get_all_cluster_exclusions() -> Dict[str, List[str]]:
    """Return the complete cluster exclusion configuration (for debugging/inspection)."""
    return CLUSTER_EXCLUSIONS.copy()
